<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="robots" content="NOINDEX,NOFOLLOW" />
<link rel="icon" href="<?php echo $this->skinUrl('favicon.ico') ?>"
	type="image/x-icon" />
<link rel="shortcut icon"
	href="<?php echo $this->skinUrl('favicon.ico') ?>" type="image/x-icon" />
<title><?php echo 'Login to Ecart administrator panel'; ?></title>
{{headStyle}} {{headLink}} {{headScript}}
<?php $this->addFilter('Placeholder') ?>
</head>
<body>

<?php echo $this->message(); ?>
<form class="form-login ecart-form"
	action="<?php echo $this->href('/auth/login');?>" method="post">
<p><label for="username"><?php echo 'Username'?></label>
<input class="input-text required" type="text" id="username"
	name="username" tabindex="1" /></p>
<p><label for="password"><?php echo 'Password'?></label>
<input class="input-text required" type="password" id="password"
	name="password" /></p>
<button type="submit" class="button btn-submit"><span>Login</span></button>
</form>

	<script type="text/javascript">
        window.onload = function() { document.getElementById('username').focus(); }
    </script>
</body>
</html>
