<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->render('html/html_head.phtml') ?>
        <title><?php echo $this->escape($this->pageTitle);?> : QuickQuick Administrator</title>
        <link rel="icon" href="<?php echo $this->skinUrl('favicon.ico') ?>" type="image/x-icon" />
        <link rel="shortcut icon" href="<?php echo $this->skinUrl('favicon.ico') ?>" type="image/x-icon" />
        
        <!-- headStyle -->
        <!-- headLink -->
        <script type="text/javascript">
        var Ecart = {
            baseUrl: '<?php echo $this->baseUrl ?>',
            skinUrl: '<?php echo $this->skinUrl ?>',
            adminUrl: '<?php echo $this->adminUrl ?>'
        };
        </script>
        <!-- headScript -->
        <script type="text/javascript">
        //Ext.namespace('Quick');
        //Ext.BLANK_IMAGE_URL = '<?php echo $this->baseUrl ?>/js/extjs/resources/images/default/s.gif';
        </script>
        <?php 
	        $this->headLink()
	            ->setUseProxy(Quick::config()->developer->enable_proxy, true);
        ?>
    </head>
    <body>
		<p>Hello ERP</p>
		<?php echo $this->layout()->content;?>
    </body>
</html>