<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->render('html/html_head.phtml') ?>
    </head>
    <body>
		<table class="callout_main" cellpadding="0" cellspacing="0">
			<tr><td colspan="2" rowspan="2">
				<table class="main_page" cellpadding="0" cellspacing="0">
				<tr><td>
					<?php echo $this->render('html/top_menu.phtml') ?>
					<?php echo $this->render('html/main_menu.phtml') ?>					
					<?php echo $this->layout()->content;?>
				</td></tr>
				</table>
				</td>
			</tr>
		</table>
		<?php echo $this->render('html/html_footer.phtml') ?>
    </body>
</html>