<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo $this->escape($this->pageTitle);?> : QuickQuick Administrator</title>
<link
	rel="icon" href="<?php echo $this->skinUrl('logo.ico') ?>"
	type="image/x-icon" />
<link
	rel="shortcut icon" href="<?php echo $this->skinUrl('logo.ico') ?>"
	type="image/x-icon" />

{{headLink}} {{headScript}}
<script type="text/javascript">
        var Quick = {
            baseUrl: '<?php echo $this->baseUrl ?>',
            skinUrl: '<?php echo $this->skinUrl ?>',
            adminUrl: '<?php echo $this->adminUrl ?>',
            requestUrl: '<?php echo $this->request ?>'
        };
        </script>
<script type="text/javascript">
        Ext.namespace('Quick');
        Ext.BLANK_IMAGE_URL = '<?php echo $this->baseUrl ?>/js/extjs/resources/images/default/s.gif';
        </script>

<?php
$this->headLink()
->setUseProxy(Quick::config()->developer->enable_proxy, true)
->appendStylesheet('js/extjs/resources/css/ext-all.css');
$this->headLink()->appendStylesheet($this->themeStyle.'/default.css');
//$this->headLink()->appendStylesheet('tabs.css');


$this->headScript()
->setUseProxy(Quick::config(Quick::config()->developer->enable_proxy, true));
$this->headScript()->offsetSetFile(-100, 'js/jquery/jquery-1.4.min.js');
$this->headScript()->offsetSetFile(-99, 'js/extjs/adapter/ext/ext-base.js');
$this->headScript()->offsetSetFile(-98, 'js/extjs/ext-all.js');
$this->headScript()->offsetSetFile(-97, 'js/quick/admin/core/translate.js');

$locale = Quick_Locale::getLocale()->toString();
$this->headScript()
->appendFile('js/quick/admin/translation/'. $locale .'/'. $this->moduleName .'.js');

$language = Quick_Locale::getLocale()->getLanguage();
if (file_exists('js/extjs/src/locale/ext-lang-' . $language . '.js')) {
	$this->headScript()->appendFile(
	                'js/extjs/src/locale/ext-lang-' . $language . '.js'
	                );
};
 
$this->addFilter('Placeholder');
?>