<table width="100%">
	<tbody>
		<tr>
			<td class="menu_group_area">
			<table width="100%">


				<tbody>
					<tr>
						<td class="menu_group_headers"><!-- Orders option Headings -->
						<table>
							<tbody>
								<tr>
									<td><img alt="" title="Transactions"
										src="/weberp-gg/css/professional/images/transactions.png"></td>
									<td class="menu_group_headers_text">Transactions</td>
								</tr>
							</tbody>
						</table>
						</td>
						<td class="menu_group_headers">
						<table>
							<tbody>
								<tr>
									<td><img alt="" title="Inquiries and Reports"
										src="/weberp-gg/css/professional/images/reports.png"></td>
									<td class="menu_group_headers_text">Inquiries and Reports</td>
								</tr>
							</tbody>
						</table>
						</td>
						<td class="menu_group_headers">
						<table>
							<tbody>
								<tr>
									<td><img alt="" title="Maintenance"
										src="/weberp-gg/css/professional/images/maintenance.png"></td>
									<td class="menu_group_headers_text">Maintenance</td>
								</tr>
							</tbody>
						</table>
						</td>
					</tr>


					<tr>
						<td class="menu_group_items"><!-- Orders transaction options -->
						<table width="100%" class="table_index">
							<tbody>
								<tr>
									<td class="menu_group_item"><a
										href="/weberp-gg/SelectOrderItems.php?&amp;NewOrder=Yes"></a>
									<li><a href="/weberp-gg/SelectOrderItems.php?&amp;NewOrder=Yes">Enter
									An Order or Quotation</a></li>
									</td>
								</tr>
								<tr>
									<td class="menu_group_item"><a
										href="/weberp-gg/SelectSalesOrder.php?"></a>
									<li><a href="/weberp-gg/SelectSalesOrder.php?">Outstanding
									Sales Orders/Quotations</a></li>
									</td>
								</tr>
								<tr>
									<td class="menu_group_item"><a
										href="/weberp-gg/SpecialOrder.php?&amp;NewSpecial=Yes"></a>
									<li><a href="/weberp-gg/SpecialOrder.php?&amp;NewSpecial=Yes">Special
									Order</a></li>
									</td>
								</tr>
								<tr>
									<td class="menu_group_item"><a
										href="/weberp-gg/SelectRecurringSalesOrder.php?"></a>
									<li><a href="/weberp-gg/SelectRecurringSalesOrder.php?">Recurring
									Order Template</a></li>
									</td>
								</tr>
								<tr>
									<td class="menu_group_item"><a
										href="/weberp-gg/RecurringSalesOrdersProcess.php?"></a>
									<li><a href="/weberp-gg/RecurringSalesOrdersProcess.php?">Process
									Recurring Orders</a></li>
									</td>
								</tr>
							</tbody>
						</table>
						</td>
						<td class="menu_group_items"><!-- Orders Inquiry options -->
						<table width="100%" class="table_index">
							<tbody>
								<tr>
									<td class="menu_group_item"><a
										href="/weberp-gg/SelectCompletedOrder.php?"></a>
									<li><a href="/weberp-gg/SelectCompletedOrder.php?">Order
									Inquiry</a></li>
									</td>
								</tr>
								<tr>
									<td class="menu_group_item"><a
										href="/weberp-gg/PDFPriceList.php?"></a>
									<li><a href="/weberp-gg/PDFPriceList.php?">Print Price Lists</a></li>
									</td>
								</tr>
								<tr>
									<td class="menu_group_item"><a
										href="/weberp-gg/PDFOrderStatus.php?"></a>
									<li><a href="/weberp-gg/PDFOrderStatus.php?">Order Status
									Reports (Print)</a></li>
									</td>
								</tr>
								<tr>
									<td class="menu_group_item"><a
										href="/weberp-gg/PDFOrdersInvoiced.php?"></a>
									<li><a href="/weberp-gg/PDFOrdersInvoiced.php?">Orders Invoiced
									Reports</a></li>
									</td>
								</tr>

								<tr>
									<td class="menu_group_item"><a
										href="/weberp-gg/PDFDeliveryDifferences.php?"></a>
									<li><a href="/weberp-gg/PDFDeliveryDifferences.php?">Order
									Delivery Differences Report</a></li>
									</td>
								</tr>
								<tr>
									<td class="menu_group_item"><a href="/weberp-gg/PDFDIFOT.php?"></a>
									<li><a href="/weberp-gg/PDFDIFOT.php?">Delivery In Full On Time
									(DIFOT) Report</a></li>
									</td>
								</tr>
								<tr>
									<td class="menu_group_item"><a
										href="/weberp-gg/SalesInquiry.php?"></a>
									<li><a href="/weberp-gg/SalesInquiry.php?">Sales Order Detail
									Or Summary Inquiries</a></li>
									</td>
								</tr>
								<tr>
									<td class="menu_group_item"></td>
								</tr>
								<tr>
									<td class="menu_group_headers">
									<div align="center">Standard Reports and Forms</div>
									</td>
								</tr>
								<tr>
									<td class="menu_group_item">There are no reports to show!</td>
								</tr>
								<tr>
									<td class="menu_group_headers">
									<div align="center">Custom Reports</div>
									</td>
								</tr>
								<tr>
									<td class="menu_group_item">There are no reports to show!</td>
								</tr>

							</tbody>
						</table>
						</td>

						<td class="menu_group_items"><!-- Orders Maintenance options -->
						<table width="100%">
							<tbody>
								<tr>
									<td></td>
								</tr>
							</tbody>
						</table>
						</td>
					</tr>
				</tbody>
			</table>
			</td>
		</tr>
	</tbody>
</table>

